[package]
name = "iot-device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aht20-driver = "1.2.0"
bmp280 = "0.4.0"
clap = { version = "4.4.10", features = ["derive"] }
rumqttc = "0.23.0"
tokio = { version = "1.34.0", features = ["rt-multi-thread"] }
